

1.   Syed Muhammad Oaun
2.   i212702 (BS-AI-J)



In [19]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [94]:
import numpy as np

class LogisticRegression:
    def __init__(self, learning_rate=0.01, max_iterations=1000, tolerance=1e-4, print_interval=10):
        self.learning_rate = learning_rate
        self.max_iterations = max_iterations
        self.tolerance = tolerance
        self.print_interval = print_interval
        self.theta = None

    def hypothesis(self, X):
        X = np.hstack((X, np.ones((X.shape[0], 1))))
        #print("h",X.shape)
        return np.dot(X, self.theta.reshape(-1, 1))


    def sigmoid(self,h):
      return 1/(1 + np.exp(-h))

    def der_cost_function(self, X, y):
        h = self.hypothesis(X)
        z = self.sigmoid(h)
        y = y.reshape(-1, 1)
        #print(h.shape)
        #print(z.shape)
        #print(y.shape)
        #print((z-h).shape)
        #print(X.shape)
        X = np.hstack((X, np.ones((X.shape[0], 1))))
        #print(X.shape)
        return np.mean((z - y) * X, axis=0)

    def cost_function(self, X, y):
        h = self.hypothesis(X)
        z = self.sigmoid(h)
        y = y.reshape(-1, 1)
        #print(z.shape)
        #print(y.shape)

        return np.mean(-(y * np.log(z) + (1 - y)* np.log(1 - z)))

    def gradient_descent(self, X, y):
        der = self.der_cost_function(X, y)
        #print("der",der.shape)
        self.theta = self.theta - self.learning_rate * der

    def get_weights(self):
        return self.theta

    def fit(self, X, y):

        num_features = X.shape[1]
        self.theta = np.zeros(num_features + 1)

        for iteration in range(1, self.max_iterations + 1):
            prev_theta = np.copy(self.theta)
            self.gradient_descent(X, y)

            if iteration % self.print_interval == 0:
                loss = self.cost_function(X, y)
                print(f"Iteration {iteration}, Loss: {loss}")
                print(f"weights ", self.theta)

            if np.linalg.norm(self.theta - prev_theta) < self.tolerance:
                print(f"Converged at iteration {iteration}")
                break

    def predict(self, X):
        h = self.hypothesis(X)
        z = self.sigmoid(h).flatten()
        return z




In [95]:
from sklearn.datasets import load_wine

# Load the dataset
wine_data = load_wine()

# Display some information about the dataset
print("Features shape:", wine_data.data.shape)
print("Target shape:", wine_data.target.shape)
print("Classes:", wine_data.target_names)


Features shape: (178, 13)
Target shape: (178,)
Classes: ['class_0' 'class_1' 'class_2']


In [96]:
from sklearn.utils import shuffle
#iris = datasets.load_iris()
X = wine_data.data[:, :]
y = wine_data.target
X,y = shuffle(X,y)

num_classes = len(np.unique(y))

print("Num_classes",num_classes,"\n")

print("Original Y\n", y,"\n")

binary_y=[]

for i in range(num_classes):

    binary_y.append((y == i).astype(int))      # class 0 is 1 every other 0
    print("binary_y_for class {}:\n{}\n".format(i, binary_y[i]))


Num_classes 3 

Original Y
 [1 0 0 1 1 0 2 2 1 1 0 1 0 2 0 2 1 0 2 0 1 0 0 0 1 0 2 2 0 0 1 1 2 0 1 1 0
 1 1 1 1 0 0 2 2 1 1 1 0 2 0 2 2 1 2 0 0 2 2 1 1 1 1 0 1 2 1 0 0 0 2 0 2 1
 1 2 1 0 1 0 1 0 2 1 0 2 1 2 2 1 0 0 0 1 1 1 2 1 1 2 2 1 2 2 2 1 1 2 1 2 2
 2 1 1 2 0 1 1 0 0 0 0 1 1 0 2 1 2 1 0 1 1 1 1 0 1 2 0 0 2 0 2 1 1 1 2 0 0
 0 2 0 1 1 1 2 1 0 2 1 1 0 2 2 0 1 0 0 0 2 1 2 0 0 1 0 1 0 1] 

binary_y_for class 0:
[0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1
 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0
 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 1
 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0 1 0]

binary_y_for class 1:
[1 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0
 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 0 0 1
 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 

# Model

In [97]:
X_train, X_test, y_train, y_test =[],[],[],[]
X_train_scaled=[]

for i in range(num_classes):

    X_tr, X_te, y_tr, y_te = train_test_split(X, binary_y[i], test_size=0.20, random_state=42)
    X_train.append(X_tr)
    X_test.append(X_te)
    y_train.append(y_tr)
    y_test.append(y_te)


    # Standardize the features
    scaler = StandardScaler()
    X_train_sc = scaler.fit_transform(X_tr)
    X_train_scaled.append(X_train_sc)
    


In [98]:
logistic_reg = []   # models to store here
predictions = []
for i in range(num_classes):

    print("\n\nMODEL {} TRAINING\n\n\n".format(i))
    
    logistic_reg.append(LogisticRegression(learning_rate=0.01, max_iterations=1000, tolerance=1e-4, print_interval=100))
    logistic_reg[i].fit(X_train_scaled[i], y_train[i])

    weights = logistic_reg[i].get_weights()
    print("Model Weights:", weights)

    X_test_scaled = scaler.transform(X_test[i])
    predictions.append(logistic_reg[i].predict(X_test_scaled))




MODEL 0 TRAINING



Iteration 100, Loss: 0.3619788602736398
weights  [ 0.21878155 -0.04046472  0.08561773 -0.18044099  0.08560596  0.17137889
  0.18860297 -0.10688333  0.07925723  0.04746026  0.07504653  0.16247216
  0.27251545 -0.16180047]
Iteration 200, Loss: 0.26275551720596013
weights  [ 0.3550642  -0.0404788   0.14922426 -0.27760254  0.11957913  0.24152149
  0.27443898 -0.14613758  0.09209642  0.07994969  0.10060166  0.24097899
  0.43557572 -0.28879698]
Iteration 300, Loss: 0.21221642379931954
weights  [ 0.45526206 -0.03051907  0.19917061 -0.34548419  0.13508251  0.27911829
  0.32732983 -0.16606914  0.08722663  0.10139592  0.11314788  0.29336082
  0.55396765 -0.39259181]
Iteration 400, Loss: 0.1803939543078145
weights  [ 0.53477137 -0.01722038  0.24009903 -0.39878231  0.14228589  0.30231095
  0.36535333 -0.17862908  0.07651858  0.11556995  0.12079022  0.33409779
  0.64776633 -0.48033971]
Iteration 500, Loss: 0.15807762081552698
weights  [ 0.60073077 -0.0027276   0.27473757 -0.44

In [80]:
def accuracy(predictions, y_true):

    print(y_true)
    correct_predictions = np.sum(predictions.round() == y_true)    # rounds to the most near value
    print(predictions.round())
    total_samples = len(y_true)
    accuracy = correct_predictions / total_samples
    return accuracy


In [81]:
for i in range(num_classes):

    print("Model {} \n {}\n".format(i,accuracy(predictions[i], y_test[i])))
    

[1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Model 0 
 1.0

[0 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1]
[0. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1.]
Model 1 
 1.0

[0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0]
[0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.]
Model 2 
 0.9166666666666666



In [82]:
def accuracy_(predictions, y_true):
        # Assuming y_true is the actual labels for the test set
        print(predictions)
        mse = np.mean((predictions - y_true) ** 2)
        accuracy = 1 - mse / np.var(y_true)
        return accuracy

In [83]:
for i in range(num_classes):

    print("Model {} \n {}\n".format(i,accuracy_(predictions[i], y_test[i])))
    

[0.95389882 0.0696683  0.03923718 0.07275303 0.00984067 0.04890862
 0.03222042 0.01710431 0.98892615 0.96361096 0.39739254 0.9829589
 0.98541168 0.144484   0.03495142 0.02499854 0.00792474 0.02526591
 0.02756559 0.94528319 0.98333279 0.09387218 0.05103453 0.99841752
 0.01587984 0.051627   0.0412504  0.24177425 0.11811027 0.01641328
 0.20855314 0.02878945 0.02712921 0.02256421 0.0255109  0.02850132]
Model 0 
 0.9452445201011306

[0.09234832 0.75358929 0.16150713 0.72315136 0.9992295  0.97830104
 0.10807816 0.97784318 0.0228685  0.14635978 0.00569691 0.07647684
 0.0508793  0.94183609 0.03557515 0.49123171 0.95673168 0.98287641
 0.93388224 0.0588036  0.02086827 0.84821853 0.76768266 0.00386653
 0.9803924  0.03672269 0.63194775 0.9392996  0.01414824 0.06954739
 0.00830039 0.20268599 0.6453013  0.85376671 0.19243651 0.67780494]
Model 1 
 0.8859202151712435

[0.05429569 0.2618128  0.92783043 0.27822373 0.00383372 0.02771451
 0.962829   0.07390997 0.06583086 0.02658677 0.97632798 0.02623163
 

# Selecting MAX Confidence one

In [116]:
def predict_1_vs_all(models,X_test):
    
    X_test_scaled = scaler.transform(X_test)
    predictions = []

    for i in range(len(models)):
    
        predictions.append(models[i].predict(X_test_scaled))


    max_index=[]
    for i in range(len(predictions[0])):
        max_index.append(np.argmax([scores[i] for scores in predictions]))

    return max_index

In [117]:
X_t, X_tes, y_t, y_tes = train_test_split(X, y, test_size=0.20, random_state=42)
p=predict_1_vs_all(logistic_reg,X_tes)

In [118]:
accuracy_(p, y_tes)

[0, 1, 0, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 2, 2, 0, 0]


0.9103362391033624

In [120]:
p

[0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 0]